### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Bubblingo0** [deimos1877/BorderlessWindow#1]
memory leaks detected with vld

**Comment by EduardDiov** [comment]
Can you be more specific? On my PC VLD doesn't detect any leaks.

**Comment by VioletGiraffe** [comment]
Just from looking at Working Set in Task Manager, it does seem as if there's a memory leak when resizing the window. Text-related? Perhaps, Qt caches rendered font glyphs of different sizes or something like that?

**Comment by VioletGiraffe** [comment]
Removing both `QLabel`s eliminates what looked like a memory leak.

**Comment by EduardDiov** [comment]
Finally was able to detect this leaks. The problem was in QMainPanel widget. Everything else was just a chain reaction, QT widgets are getting destroyed with their parent, and their parent was leaking.

Tnx for reporting guys.
