### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by mkrautz** [deimos1877/BorderlessWindow#3]
Most of the code in this repository has no license, so it is unclear how it can be used in open source projects.

It would be great if you would release this code under an open source license!

**Comment by EduardDiov** [comment]
Done.

**Comment by mkrautz** [comment]
Not sure if not having a name or pseudonym in the Copyright (C) line was intended? That would help, too. :-)

Sorry for all the trouble! :-)

**Comment by EduardDiov** [comment]
Done. Thank you for pointing this out.
