### ISSUE TITLE
Is there any way to create a round corner for this window?

### ISSUE THREAD

**Issue by woodywu** [deimos1877/BorderlessWindow#4]
Hi,

This project is so cool. I learnt a lot from it. However, I can't found a way to create a round corner for the window. Could you give me a help?

Thank you so much!

**Comment by EduardDiov** [comment]
Hi.

Sorry, my project doesn't support round corners. The goal was to create window like in Visual Studio 2012 or Office 2013.

You probably should take a look at creating custom shaped windows using WinAPI. But i'm not sure, I don't have any experience in this area.

**Comment by woodywu** [comment]
Thanks anyway.
