### ISSUE TITLE
SystemMenu(Alt+Space) Minimize & Maximize doesn't trigger functions

### ISSUE THREAD

**Issue by IMAN4K** [deimos1877/BorderlessWindow#5]
Hi dear @deimos1877 
Thanks for sharing your snippets.
Sounds like the sysmenu(Alt+Space) doesn't work.
https://github.com/deimos1877/BorderlessWindow/blob/master/MainWindow.cpp#L92-L97

**Comment by IMAN4K** [comment]
[This](https://github.com/deimos1877/BorderlessWindow/pull/6) Should make changes

**Comment by EduardDiov** [comment]
Hello. Sorry for not replying sooner, was busy with other stuff.

I've found some other small bugs with system menu. I've applied your patch and reworked my code. Now it should work fine.

Thanks for your contribution.
